In [1]:
# Standardization and Normalization

In [2]:
# Scaling
# Salary :  10K , 1L , 10L    / 10L  =>   0.01 , 0.1 , 1
# Age :  54 ,  67 , 45   / 100  =>     0.54 , 0.67 , 0.45

In [3]:
# Standardization (it is good to go with Standardization if you have outlier in your dataset)
# z = (x(data)-miu(mean))/sigma(std)

In [4]:
data = {
    'Empid':[ x for x in range(101,111) ],
    'Empsalary':[23445,78786,78987,932455,67554,78987,23244,67865,34554,67876]
}

In [5]:
import pandas as pd

In [13]:
df = pd.DataFrame(data)

In [7]:
df

   Empid  Empsalary
0    101      23445
1    102      78786
2    103      78987
3    104     932455
4    105      67554
5    106      78987
6    107      23244
7    108      67865
8    109      34554
9    110      67876

In [8]:
df['scaleSalary'] = (df['Empsalary']-df['Empsalary'].mean())/df['Empsalary'].std()

In [9]:
df

   Empid  Empsalary  scaleSalary
0    101      23445    -0.439445
1    102      78786    -0.239992
2    103      78987    -0.239268
3    104     932455     2.836688
4    105      67554    -0.280473
5    106      78987    -0.239268
6    107      23244    -0.440169
7    108      67865    -0.279352
8    109      34554    -0.399407
9    110      67876    -0.279313

In [10]:
df.scaleSalary.max()

np.float64(2.836688143149149)

In [11]:
df = df[df.scaleSalary<df.scaleSalary.max()]

In [12]:
df

   Empid  Empsalary  scaleSalary
0    101      23445    -0.439445
1    102      78786    -0.239992
2    103      78987    -0.239268
4    105      67554    -0.280473
5    106      78987    -0.239268
6    107      23244    -0.440169
7    108      67865    -0.279352
8    109      34554    -0.399407
9    110      67876    -0.279313

In [14]:
df

   Empid  Empsalary
0    101      23445
1    102      78786
2    103      78987
3    104     932455
4    105      67554
5    106      78987
6    107      23244
7    108      67865
8    109      34554
9    110      67876

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
newdf = StandardScaler().fit_transform(df)

In [17]:
newdf

array([[-1.5666989 , -0.4632157 ],
       [-1.21854359, -0.25297411],
       [-0.87038828, -0.25221051],
       [-0.52223297,  2.99013185],
       [-0.17407766, -0.29564471],
       [ 0.17407766, -0.25221051],
       [ 0.52223297, -0.4639793 ],
       [ 0.87038828, -0.29446321],
       [ 1.21854359, -0.42101238],
       [ 1.5666989 , -0.29442142]])

In [19]:
df.describe()

           Empid     Empsalary
count   10.00000      10.00000
mean   105.50000  145375.30000
std      3.02765  277464.30354
min    101.00000   23244.00000
25%    103.25000   42804.00000
50%    105.50000   67870.50000
75%    107.75000   78936.75000
max    110.00000  932455.00000

In [29]:
# Normalization
# z = (x-min)/(max-min)

In [21]:
df = df[df['Empsalary']<500000]

In [22]:
df

   Empid  Empsalary
0    101      23445
1    102      78786
2    103      78987
4    105      67554
5    106      78987
6    107      23244
7    108      67865
8    109      34554
9    110      67876

In [26]:
df['scaleSalary'] = (df['Empsalary']-df['Empsalary'].min())/(df['Empsalary'].max()-df['Empsalary'].min())

C:\Users\Croma Campus\AppData\Local\Temp\ipykernel_1912\1711576659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['scaleSalary'] = (df['Empsalary']-df['Empsalary'].min())/(df['Empsalary'].max()-df['Empsalary'].min())

In [27]:
df

   Empid  Empsalary  scaleSalary
0    101      23445     0.003606
1    102      78786     0.996394
2    103      78987     1.000000
4    105      67554     0.794898
5    106      78987     1.000000
6    107      23244     0.000000
7    108      67865     0.800477
8    109      34554     0.202895
9    110      67876     0.800675

In [31]:
df = df.drop(columns=['scaleSalary'])

In [32]:
df

   Empid  Empsalary
0    101      23445
1    102      78786
2    103      78987
4    105      67554
5    106      78987
6    107      23244
7    108      67865
8    109      34554
9    110      67876

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
df = MinMaxScaler().fit_transform(df)

In [35]:
df

array([[0.        , 0.00360583],
       [0.11111111, 0.99639417],
       [0.22222222, 1.        ],
       [0.44444444, 0.79489801],
       [0.55555556, 1.        ],
       [0.66666667, 0.        ],
       [0.77777778, 0.80047719],
       [0.88888889, 0.20289543],
       [1.        , 0.80067452]])