In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel(r"C:\Users\Croma Campus\Downloads\Financial_Sample (5).xlsx")

In [4]:
df.shape

(700, 16)

In [7]:
df = df.bfill()

In [8]:
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount Band          0
Units Sold             0
Manufacturing Price    0
Sale Price             0
Gross Sales            0
Discounts              0
 Sales                 0
COGS                   0
Profit                 0
Date                   0
Month Number           0
Month Name             0
Year                   0
dtype: int64

In [9]:
df.head(2)

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014

In [11]:
df['Gross Sales'].max()

np.float64(1207500.0)

In [ ]:
# Encoding
# Text Dataset (Two Types)
# - Normal Text   (Delhi , Noida , GZB etc)
# - Ordinal Text  (Small , Large , Medium , XLarge)

In [12]:
df.Product.unique()

array(['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla'],
      dtype=object)

In [15]:
df['Discount Band'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [16]:
# Encoding (Types)
# 1- OneHotEncoding
# 2- OrdinalEncoding
# 3- LabelEncoding

In [17]:
db = ['Low', 'Medium', 'High']

In [18]:
df['Discount Band']

0       Low
1       Low
2       Low
3       Low
4       Low
       ...
695    High
696    High
697    High
698    High
699    High
Name: Discount Band, Length: 700, dtype: object

In [19]:
df['Discount Band'] = df['Discount Band'].map( lambda val:db.index(val) )

In [20]:
df['Discount Band']

0      0
1      0
2      0
3      0
4      0
      ..
695    2
696    2
697    2
698    2
699    2
Name: Discount Band, Length: 700, dtype: int64

In [22]:
# !pip install scikit-learn

In [25]:
df = pd.read_excel(r"C:\Users\Croma Campus\Downloads\Financial_Sample (5).xlsx").bfill()

In [26]:
df['Discount Band']

0       Low
1       Low
2       Low
3       Low
4       Low
       ...
695    High
696    High
697    High
698    High
699    High
Name: Discount Band, Length: 700, dtype: object

In [27]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
encoder = OrdinalEncoder( categories=[['Low', 'Medium', 'High']] )

In [29]:
df['Discount Band'] = encoder.fit_transform(df[['Discount Band']])

In [30]:
df['Discount Band']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
695    2.0
696    2.0
697    2.0
698    2.0
699    2.0
Name: Discount Band, Length: 700, dtype: float64

In [31]:
df['Country']

0                        Canada
1                       Germany
2                        France
3                       Germany
4                        Mexico
                 ...
695                      France
696                      Mexico
697                      Mexico
698                      Canada
699    United States of America
Name: Country, Length: 700, dtype: object

In [32]:
df['Country'].unique()

array(['Canada', 'Germany', 'France', 'Mexico',
       'United States of America'], dtype=object)

In [33]:
df['Country'] = df['Country'].map( lambda val: list(df['Country'].unique()).index(val) )

In [34]:
df['Country']

0      0
1      1
2      2
3      1
4      3
      ..
695    2
696    3
697    3
698    0
699    4
Name: Country, Length: 700, dtype: int64

In [37]:
df = pd.read_excel(r"C:\Users\Croma Campus\Downloads\Financial_Sample (5).xlsx").bfill()

In [38]:
df['Country']

0                        Canada
1                       Germany
2                        France
3                       Germany
4                        Mexico
                 ...
695                      France
696                      Mexico
697                      Mexico
698                      Canada
699    United States of America
Name: Country, Length: 700, dtype: object

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
encoder = LabelEncoder()

In [39]:
df['Country'] = encoder.fit_transform(df[['Country']])

C:\Users\Croma Campus\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [40]:
df['Country']

0      0
1      2
2      1
3      2
4      3
      ..
695    1
696    3
697    3
698    0
699    4
Name: Country, Length: 700, dtype: int64

In [41]:
df['Segment']

0            Government
1            Government
2             Midmarket
3             Midmarket
4             Midmarket
             ...
695      Small Business
696      Small Business
697          Government
698          Government
699    Channel Partners
Name: Segment, Length: 700, dtype: object

In [42]:
df['Segment'].unique()

array(['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
       'Small Business'], dtype=object)

In [43]:
def OneHotEncoding(val):
    df[val] = df['Segment'].map(lambda seg: 1 if seg==val else 0)

In [45]:
for val in df['Segment'].unique():
    OneHotEncoding(val)

In [46]:
df.shape

(700, 21)

In [47]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,...,Profit,Date,Month Number,Month Name,Year,Government,Midmarket,Channel Partners,Enterprise,Small Business
0,Government,0,Carretera,Low,1618.5,3,20.0,32370.0,0.0,32370.0,...,16185.0,2014-01-01,1,January,2014,1,0,0,0,0
1,Government,2,Carretera,Low,1321.0,3,20.0,26420.0,0.0,26420.0,...,13210.0,2014-01-01,1,January,2014,1,0,0,0,0
2,Midmarket,1,Carretera,Low,2178.0,3,15.0,32670.0,0.0,32670.0,...,10890.0,2014-06-01,6,June,2014,0,1,0,0,0
3,Midmarket,2,Carretera,Low,888.0,3,15.0,13320.0,0.0,13320.0,...,4440.0,2014-06-01,6,June,2014,0,1,0,0,0
4,Midmarket,3,Carretera,Low,2470.0,3,15.0,37050.0,0.0,37050.0,...,12350.0,2014-06-01,6,June,2014,0,1,0,0,0

In [48]:
df.Product

0      Carretera
1      Carretera
2      Carretera
3      Carretera
4      Carretera
         ...
695     Amarilla
696     Amarilla
697      Montana
698        Paseo
699          VTT
Name: Product, Length: 700, dtype: object

In [49]:
df.Product.unique()

array(['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla'],
      dtype=object)

In [50]:
from sklearn.preprocessing import OneHotEncoder

In [51]:
encoder = OneHotEncoder( sparse_output=False )

In [54]:
encoded_df = encoder.fit_transform(df[['Product']])

In [55]:
encoded_df

array([[0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], shape=(700, 6))

In [56]:
encoded_df = pd.DataFrame( encoded_df , columns=encoder.get_feature_names_out() )

In [57]:
encoded_df

,Product_Amarilla,Product_Carretera,Product_Montana,Product_Paseo,Product_VTT,Product_Velo
0,0.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...
695,1.0,0.0,0.0,0.0,0.0,0.0
696,1.0,0.0,0.0,0.0,0.0,0.0
697,0.0,0.0,1.0,0.0,0.0,0.0
698,0.0,0.0,0.0,1.0,0.0,0.0
699,0.0,0.0,0.0,0.0,1.0,0.0